server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: chat-service

spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:chat_db}
      username: ${MONGO_USER:}
      password: ${MONGO_PASSWORD:}
      authentication-database: ${MONGO_AUTH_DB:chat_db}
