server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: iam-service

authorization:
  legacy-jwt:
    enabled: ${LEGACY_JWT_ENABLED:true}
  legacy-jwks:
    enabled: ${LEGACY_JWKS_ENABLED:true}
  jwt:
    private-key: ${JWT_PRIVATE_KEY:}
    public-key: ${JWT_PUBLIC_KEY:}
    private-key-path: ${JWT_PRIVATE_KEY_PATH:}
    public-key-path: ${JWT_PUBLIC_KEY_PATH:}
    expiration:
      days: ${JWT_EXPIRATION_DAYS:7}

auth0:
  issuer-uri: ${AUTH0_ISSUER_URI:https://auth0.local/}
  audience: ${AUTH0_AUDIENCE:jameofit-api}

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: pe.edu.upc.iam_service.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
    show-sql: true
