server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: iam-service

authorization:
  jwt:
    private-key-path: ${JWT_PRIVATE_KEY_PATH:file:/app/secrets/jwt.key}
    public-key-path: ${JWT_PUBLIC_KEY_PATH:file:/app/secrets/jwt.key.pub}
    expiration:
      days: ${JWT_EXPIRATION_DAYS:7}

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: pe.edu.upc.iam_service.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
    show-sql: true
