server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: profiles-service

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: "http://iam-service:8081/api/v1/jwks/.well-known/jwks.json"

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # 'validate' o 'none' en producción
      naming:
        physical-strategy: pe.edu.upc.profiles_service.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
    show-sql: true
